title: Nikodemus Pellerin Nilsson Ohm - E-portfolio
logo: /assets/profil_bild.jpg
description: E-portfolio för Nikodemus Pellerin Nilsson Ohm, student på KTH.
show_downloads: true
theme: jekyll-theme-minimal
