title: Nikodemus Pellerin Nilsson Ohm
logo: /assets/profil_bild.jpg
description: Civilingenjörsstudent i Informationsteknik på KTH. Intresserad av mjukvaruutveckling och programmering i Python, Javasctipt, Html och Java. Tidigare praktik hos Saab.
show_downloads: true
theme: jekyll-theme-minimal
